### ISSUE TITLE
`update_records()` fails for data type multiple select.

### ISSUE THREAD

**Issue by mspittler** [matthewjrogers/rairtable#2]
I have noticed that `batch_encode_post()` called from `update_records()` returns malformed JSON for the data type Multiple Select which is an Array of Strings.  For a given tibble, e.g.

```r
tibble(
  airtable_record_id = "recQAGljdD111pHOb",
  Preferences = list(c("Men", "Babies"))
)
```
`batch_encode_post()` returns:

```json
"{\"records\":[{\"id\":\"recQAGljdD111pHOb\",\"fields\":{\"Preferences\":[[\"Men\",\"Babies\"]]}}]}"
```
but it should be formed as:
```json
"{\"records\":[{\"id\":\"recQAGljdD111pHOb\",\"fields\":{\"Preferences\":[\"Men\",\"Babies\"]}}]}"
```

I could gaffer tape it by adding the following after line 57 in `update_records.R`, but this is of course no solution:

```r
library(magrittr)
batch_json_requests %<>%
    stringr::str_replace_all(fixed(":[["), fixed(":[")) %>% 
    stringr::str_replace_all(fixed("]]}"), fixed("]}"))
```

Thanks for the package!

**Comment by matthewjrogers** [comment]
Thanks for the flag @mspittler, I'll take a look at this. I suspect that values will need to be wrapped in a call to `unlist` somewhere in the code to get to the proper formatting.

I'll let you know when this is resolved!

**Comment by matthewjrogers** [comment]
Hey there @mspittler. I just pushed changes to the dev branch to address this issue. You should be able to install the update using `remotes::install_github('matthewjrogers/rairtable', ref = 'dev')`, and changes will be reflected on CRAN in the next few months.

I added this line of processing in `encode_batch_patch` to solve the issue, which is just unlisting any list greater than length 1. The length check is because the API expects a list with a single element if only one option is selected

```
lapply(record_batch[['records']][[idx]], function(r) if (is.list(r) & length(r[[1]]) > 1) unlist(r) else r)
```
