### ISSUE TITLE
Downloading only fields included in a View

### ISSUE THREAD

**Issue by timothoms** [matthewjrogers/rairtable#6]
**Is your feature request related to a problem? Please describe.**

I mistakenly assumed that reading data based on an Airtable object for a view would only include the fields in that view (in addition to including only the records in that view). Currently, the read_airtable() function downloads the entire underlying table (with the exception of empty fields, which alerted me to this behaviour). Including only the fields that are not hidden in the Airtable view is useful because it would allow limiting the data to access via the Airtable API in the case of very large tables. 

**Describe the solution you'd like**

A good solution would be to only download the fields that are shown in the view, if the Airtable API makes this possible. 

**Describe alternatives you've considered**

An alternative solution would be to specify the fields to include in the download with a character vector of field names. This would provide fine-grained programmatic control, but it a bit less user-friendly, especially for tables with many fields. 

Thank you!

**Comment by timothoms** [comment]
Also, would it be possible to include empty fields (i.e. existing fields in the Airtable base that do not yet contain any data) as empty columns in the resulting dataframe?

**Comment by matthewjrogers** [comment]
Hi @timothoms -- the behavior you describe is also how I imagined reading a view would work. I will investigate the feasibility of this, likely around the new year when I have some time off. My suspicion is that views don't actually pay attention to what columns are hidden or visible.

In the event that the only solution is providing a list of column names to download, my inclination off the cuff is to simply recommend using a `dplyr`  solution, since it boils down to more or less the same thing (the user providing a list of column names to keep). For example:

```
atb <- airtable("Table 1", "appXXXXXXXXXXXXX")

dat <- read_airtable(atb) %>%
                select(airtable_record_id, col1, col2, ...)
```

In regards to your second question, I recall investigating this a while ago and I do not think it is possible to force the API to return empty columns. There's nothing in `rairtable` to deliberately exclude empty columns, so if they aren't showing up in the output, it's because the Airtable API is excluding them.

**Comment by timothoms** [comment]
Thank you for the response, @matthewjrogers. The work-around is what I have done so far, but for large Airtable bases, this makes for a lot of transaction costs. So this would be a good enhancement. As to the second point, this is what I had suspected -- that those empty fields are simply not included in the API response.  Thanks again for the package.

**Comment by matthewjrogers** [comment]
That's a fair point, I missed that in your original feature request. I will investigate if views can be used to control which columns are downloaded, as I agree that would be a better user experience. The good news is that I'm 100% sure it's possible to specify which fields to download, as I've seen that implemented elsewhere.

More than welcome for the package -- glad it's being used!

**Comment by matthewjrogers** [comment]
https://community.airtable.com/t/api-call-displays-also-hidden-fields/29420/3

Looks like I may be priced into just providing an optional 'fields' argument

**Comment by timothoms** [comment]
Good to have the suspicion confirmed. One of the many ways that the userfriendliness of Airtable comes with significant limitations. The optional "fields" argument is the way to go. Thanks!

**Comment by matthewjrogers** [comment]
@timothoms this is resolved in `dev`. To access the changes, you can install with `remotes::install_github('matthewjrogers/rairtable', ref = 'dev')`. I'm going to send updates to CRAN in the next week.
